// Integration test for whole-program recompilation: a recompiled program
// (generated at build time) whose main function calls a second function
// through the runtime dispatch table. Proves function discovery + ppc_call
// dispatch + inter-function calls work together.
#include <cstdio>

#include "gcrt/ppc.h"

// Generated by make_program.py: registers func_80003100 and func_80003110.
extern "C" void ppc_register_all(void);

using namespace gcrt;

int main() {
    int failures = 0;
    auto check = [&](bool cond, const char* what) {
        if (!cond) {
            std::fprintf(stderr, "FAIL: %s\n", what);
            ++failures;
        }
    };

    PpcClearFunctions();
    PpcResetUnimplementedCount();
    ppc_register_all();  // populate the dispatch table from the recompiled TU

    PpcContext ctx;
    for (int i = 0; i < 32; ++i) {
        ctx.gpr[i] = 0;
        ctx.fpr[i].f64 = 0.0;
    }
    ctx.lr = ctx.ctr = ctx.cr = ctx.xer = 0;

    // Enter at main; it calls the add function (r3 = 42) then adds 1 -> 43.
    ppc_call(&ctx, 0x80003100);
    check(ctx.gpr[3] == 43, "inter-function call produced r3 == 43");
    check(PpcUnimplementedCount() == 0, "no unimplemented instructions hit");

    // The callee is independently reachable through the same table.
    PpcContext ctx2;
    for (int i = 0; i < 32; ++i) {
        ctx2.gpr[i] = 0;
        ctx2.fpr[i].f64 = 0.0;
    }
    ctx2.lr = ctx2.ctr = ctx2.cr = ctx2.xer = 0;
    ppc_call(&ctx2, 0x80003110);
    check(ctx2.gpr[3] == 42, "callee reachable directly, r3 == 42");

    if (failures == 0) {
        std::printf("gcrt ppc program test: all checks passed\n");
        return 0;
    }
    std::fprintf(stderr, "gcrt ppc program test: %d failure(s)\n", failures);
    return 1;
}
